### ISSUE TITLE
Remove ENF.CONT.COEN.ENFE.PR

### ISSUE THREAD

**Issue by tgherzog** [worldbank/ESG_gaps_research#10]
@andreiilas let's remove `ENF.CONT.COEN.ENFE.PR` from the database and the analysis. This indicator is essentially the equivalent of `ENF.CONT.COEN.COST.ZS` but it isn't referenced in any data product that I can see. It seems to have been added by accident.

Once this is removed then the number of indicators in the metadata database comes to 134, and the list is identical to the master study list.

**Comment by andreiilas** [comment]
Done
