### ISSUE TITLE
Remove "Retirement Age" from the analysis?

### ISSUE THREAD

**Issue by tgherzog** [worldbank/ESG_gaps_research#6]
"Retirement Age" is the one indicator without a CETS code and that does not exist in the API. We should either remove it from the area of study, or its metadata needs to be sufficient that we can do a proper analysis on it. "Retirement Age" comes from [this database][wbl] which was last updated in 2/2019 and has values for 2018. But currently it is flagged as discontinued (expl_a=1).

[wbl]: https://datacatalog.worldbank.org/dataset/women-business-and-law

**Comment by tgherzog** [comment]
@andreiilas @randrescastaneda let me know your thoughts on this. I'm fine to remove it for the sake of simplicity.

**Comment by andreiilas** [comment]
If you tracked it to a database and it is updated, I would keep it. I modified it to 0 for all expl

**Comment by tgherzog** [comment]
>I modified it to 0 for all expl

@andreiilas I don't think that's the correct approach though. I updated the `coverage.py` so that it can run from data sources not in the API. It's showing the WBL has retirement age data for 41 countries, well short of the "ideal" case.

I think that Retirement Age should be TRUE for EXP_F (survey dependence) and EXP_G (low coverage/irrelevant for high income countries). The series is missing data for 86% of HICs; one could argue that the established retirement age is not an issue there.

**Comment by andreiilas** [comment]
Thanks again. I coded it as true for F and G.

**Comment by tgherzog** [comment]
Closing this issue. The data builder function includes this data series now.
