### ISSUE TITLE
Logic for expl_a is incorrect

### ISSUE THREAD

**Issue by tgherzog** [worldbank/ESG_gaps_research#7]
Logic behind the boolean values for expl_a is incorrect. Only database 57 and 11 are no longer maintained. All other databases should be assigned FALSE|0. At least some (but not all) indicators from 59, 75 (which is the ESG dataset) and possibly other databases are assigned TRUE|1.

"Retirement Age" - the one indicator not in the API back-end and thus without a CETS code - should be assigned FALSE|0 for expl_a - if we decide to [keep it at all](6)

**Comment by andreiilas** [comment]
There are 7 indicators that do not belong to database 27 and 11 that are coded 1 for explanation a. This  followed the interviews that I had with Vinny (has 6 indicators) and Florina (1).

**Comment by tgherzog** [comment]
>There are 7 indicators that do not belong to database 27 and 11 that are coded 1 for explanation a.

I assume database 27 should be database 57 in your comment.

>This followed the interviews that I had with Vinny (has 6 indicators) and Florina (1).

@andreiilas I think you are confusing EXP_A with EXP_B. If an indicator is in an actively maintained database but has not been updated, that is B not A. The 2 explanations are mutually exclusive.

EN.CLC.SPEI.XD
EN.CLC.PRCP.XD
EN.CLC.HEAT.XD
EN.CLC.CDDY.XD

These 4 come from the Climate Knowledge Portal which is actively maintained. 3 of the 4 are in the newly created ESG dataset, so they should be coded 0 for both EXP_B and EXP_A.

NW.NCA.SACO.TO
NW.NCA.SAGA.TO

These 2 come from the Wealth Accounts database (59) which was last updated in 2018. The indicators themselves have MRVs of 2014 so this should be coded EXP_B not EXP_A

SN.ITK.DFCT

This one is currently in database 57 so it is correctly coded as EXP_A, but in your database the `database_id` column lists it as 2 which is incorrect.

**Comment by andreiilas** [comment]
Thanks, Tim. Coding for A&B is now clearer. I updated it and created a pull request.
