### ISSUE TITLE
Logic for expl_b

### ISSUE THREAD

**Issue by tgherzog** [worldbank/ESG_gaps_research#8]
A few indicators should be `expl_b=1` that are currently 0:

EN.ATM.GHGT.KT.CE (MRV=2012)
EN.ATM.NOXE.KT.CE (MRV=2012)

A few more that should also be `expl_b=1` but currently aren't perhaps because in some cases they are erroneously `expl_a=1` see #7:

EN.ATM.METH.PC
EN.ATM.NOXE.PC
NW.NCA.SACO.TO
NW.NCA.SAGA.TO
NW.NCA.SAOI.TO

**Comment by andreiilas** [comment]
This should be solved now.
