### ISSUE TITLE
Assignment of expl_g

### ISSUE THREAD

**Issue by tgherzog** [worldbank/ESG_gaps_research#9]
Many discrepancies in expl_g between the values and the analysis on which it is supposed to be based. See attachment.

[ESG Data Comparison Matrix-2019b.xlsx](https://github.com/worldbank/ESG_gaps_research/files/3765882/ESG.Data.Comparison.Matrix-2019b.xlsx)

**Comment by tgherzog** [comment]
We need a separate conversation on which of these indicators should be switched from 1 to 0 for expl_g but we first need to fix the problem above.

**Comment by andreiilas** [comment]
I corrected this issue and pushed it to the rep on GitKraken

**Comment by tgherzog** [comment]
I'm reopening this issue.

First, in the spreadsheet above I count 42 countries that should nominally be coded 1 for EXP_G, but there are only 30 in the latest database. 3 of those 12 countries have EXP_B=1 which leaves 9 remaining:

```
IC.FRM.OUTG.ZS
IP.PAT.RESD
MS.MIL.XPND.GD.ZS
NY.ADJ.DFOR.GN.ZS
NY.ADJ.DPEM.GN.ZS
SH.DTH.COMM.ZS
SH.STA.MMRT
SN.ITK.DEFC.ZS
TX.MNF.TECH.ZS.UN
```

Let's discuss at our 2pm meeting today. I first want to make sure there's not an error on my part.

**Comment by tgherzog** [comment]
For discussion: here is a list of indicators where we're missing 80%+ of HIC countries:

CETSID | Description
-- | --
DT.ODA.ODAT.CD | Net official development   assistance received (current US$)
SH.MLR.INCD.P3 | Incidence of malaria (per 1,000   population at risk)
SI.POV.NAHC | Poverty headcount ratio at   national poverty lines (% of population)
SL.TLF.0714.ZS | Children in employment, total (%   of children ages 7-14)
SP.UWT.TFRT | Unmet need for contraception (%   of married women ages 15-49)

Except for possibly SI.POV.NAHC I'm fine to apply EXP_G to all of these on the basis that the values are not interesting for HICs.

Here is the same list for low-population countries (POP<100,000), and I've marked the ones I think are still relevant to small economies (i.e., EXP_G should be changed to 0):

CETSID | Description | Relevant?
-- | -- | --
EG.ELC.COAL.ZS | Electricity production from coal   sources (% of total) |  
EG.ELC.NUCL.ZS | Electricity production   from nuclear sources (% of total)
EG.IMP.CONS.ZS | Energy imports, net (% of energy use) |  
EN.CLC.GHGR.MT.CE | GHG net   emissions/removals by LUCF (Mt of CO2 equivalent)
EN.CLC.MDAT.ZS | Droughts, floods, extreme temperatures (% of population,   average 1990-2009) | 1
ER.H2O.FWTL.ZS | Annual freshwater   withdrawals, total (% of internal resources)
GFDD.DM.06 | Outstanding international   public debt securities to GDP (%)
IC.FRM.OUTG.ZS | Value lost due to electrical outages (% of sales for affected   firms) | 1
IP.PAT.RESD | Patent applications, residents |  
MS.MIL.XPND.GD.ZS | Military expenditure (% of GDP) |  
NY.ADJ.DFOR.GN.ZS | Adjusted savings: net forest depletion (% of GNI) |  
NY.ADJ.DPEM.GN.ZS | Adjusted savings:   particulate emission damage (% of GNI)
NY.ADJ.DRES.GN.ZS | Adjusted savings: natural   resources depletion (% of GNI)
SH.DTH.COMM.ZS | Cause of death, by communicable diseases and maternal,   prenatal and nutrition conditions (% of total) | 1
SH.DYN.AIDS.ZS | Prevalence of HIV, total (% of population ages 15-49) | 1
SH.MLR.INCD.P3 | Incidence of malaria (per 1,000 population at risk) | 1
SH.STA.MMRT | Maternal mortality ratio (modeled estimate, per 100,000 live   births) | 1
SI.DST.FRST.20 | Income share held by lowest 20% | 1
SI.POV.DDAY | Poverty headcount ratio at $1.90 a day (2011 PPP) (% of   population) | 1
SI.POV.GINI | GINI index (World Bank estimate) | 1
SI.POV.NAHC | Poverty headcount ratio at national poverty lines (% of   population) | 1
SI.SPR.PCAP.ZG | Annualized average growth rate in per capita real survey mean   consumption or income, total population (%) | 1
SL.EMP.1524.SP.ZS | Employment to population ratio, ages 15-24, total (%) (modeled   ILO estimate) | 1
SL.EMP.VULN.ZS | Vulnerable employment, total (% of total employment) (modeled   ILO estimate) | 1
SL.TLF.0714.ZS | Children in employment, total (% of children ages 7-14) | 1
SL.TLF.ACTI.ZS | Labor force participation rate, total (% of total population   ages 15-64) (modeled ILO estimate) | 1
SL.TLF.CACT.FM.ZS | Ratio of female to male labor force participation rate (%)   (modeled ILO estimate) | 1
SL.UEM.1524.ZS | Unemployment, youth total (% of total labor force ages 15-24)   (modeled ILO estimate) | 1
SL.UEM.TOTL.FE.ZS | Unemployment, female (% of female labor force) (modeled ILO   estimate) | 1
SL.UEM.TOTL.ZS | Unemployment, total (% of total labor force) (modeled ILO   estimate) | 1
SM.POP.NETM | Net migration |  
SN.ITK.DEFC.ZS | Prevalence of undernourishment (% of population) | 1
SP.POP.65UP.TO.ZS | Population ages 65 and above (% of total population) | 1
SP.POP.SCIE.RD.P6 | Researchers in R&D (per million people) | 1
SP.POP.TECH.RD.P6 | Technicians in R&D (per million people) | 1
SP.UWT.TFRT | Unmet need for contraception (% of married women ages 15-49) | 1
TX.MNF.TECH.ZS.UN | Medium and high-tech   exports (% manufactured exports)

**Comment by andreiilas** [comment]
[ESG.Data.Comparison.Matrix-2019b (3).xlsx](https://github.com/worldbank/ESG_gaps_research/files/3811230/ESG.Data.Comparison.Matrix-2019b.3.xlsx)

The problem came from a faulty selection in excel when I sorted by color. It would keep the cetsid constant while changing the other variables. 

In total there are 41 indicators with G, from which I deleted 6 that were coded B due to MRV 2014 or earlier.

**Comment by tgherzog** [comment]
@andreiilas - you should have 42 indicators less 6 coded B for a total of 36. Don't forget the Retirement Age indicator (WBL) should also be coded G as discussed on #9

**Comment by andreiilas** [comment]
thanks Tim. I updated it.

**Comment by tgherzog** [comment]
This is an update to [this comment](#issuecomment-549934388) but with the small economy threshold set to 120,000 population as we discussed. The net effect was to flag 6 HIC countries and 30 small economy countries (excluding those that had already been flagged EXP_A or EXP_B).

HIC countries are as follows:

ID | DESCRIPTION
--- | ---
DT.ODA.ODAT.CD | Net official development assistance   received (current US$)
SH.MLR.INCD.P3 | Incidence of malaria (per 1,000 population at risk)
SI.POV.NAHC | Poverty headcount ratio at national poverty lines (% of population)
SL.TLF.0714.ZS | Children in employment, total (% of children ages 7-14)
SP.UWT.TFRT | Unmet need for contraception (% of married women ages 15-49)
WBL | Retirement Age

Let's have a quick discussion about these; the two I can imagine being non-trivial for HICs are SI.POV.NAHC, SP.UWT.TFRT and possibly "Retirement Age"

The small economy indicators look like this . The ones where I've put "1" in column 3 are the ones that I'm suggesting may be "false positives," that is, they are non-trivial for small economies. Column 4 shows which indicators are being flagged as possibly trivial for HIC countries.

ID | DESCRIPTION | NON-TRIVIAL | IS_RICH
--- | --- | ---
EG.ELC.COAL.ZS | Electricity production from coal sources (%   of total) | 0 |  
EG.ELC.NUCL.ZS | Electricity production from nuclear sources (% of total) | 0 |  
EG.IMP.CONS.ZS | Energy imports, net (% of energy use) | 0 |  
GFDD.DM.06 | Outstanding international public debt securities to GDP (%) | 0 |  
IP.PAT.RESD | Patent applications, residents | 0 |  
MS.MIL.XPND.GD.ZS | Military expenditure (% of GDP) | 0 |  
NY.ADJ.DPEM.GN.ZS | Adjusted savings: particulate emission damage (% of GNI) | 0 |  
NY.ADJ.DRES.GN.ZS | Adjusted savings: natural resources depletion (% of GNI) | 0 |  
SH.DYN.AIDS.ZS | Prevalence of HIV, total (% of population ages 15-49) | 1 |  
SH.MLR.INCD.P3 | Incidence of malaria (per 1,000 population at risk) | 1 | 1
SH.STA.SMSS.ZS | People using safely managed sanitation services (% of population) | 1 |  
SI.DST.FRST.20 | Income share held by lowest 20% | 1 |  
SI.POV.DDAY | Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population) | 1 |  
SI.POV.GINI | GINI index (World Bank estimate) | 1 |  
SI.POV.NAHC | Poverty headcount ratio at national poverty lines (% of population) | 1 | 1
SI.SPR.PCAP.ZG | Annualized average growth rate in per capita real survey mean consumption   or income, total population (%) | 1 |  
SL.EMP.1524.SP.ZS | Employment to population ratio, ages 15-24, total (%) (modeled ILO   estimate) | 1 |  
SL.EMP.VULN.ZS | Vulnerable employment, total (% of total employment) (modeled ILO   estimate) | 1 |  
SL.TLF.0714.ZS | Children in employment, total (% of children ages 7-14) | 1 | 1
SL.TLF.ACTI.ZS | Labor force participation rate, total (% of total population ages 15-64)   (modeled ILO estimate) | 1 |  
SL.TLF.CACT.FM.ZS | Ratio of female to male labor force participation rate (%) (modeled ILO   estimate) | 1 |  
SL.UEM.1524.ZS | Unemployment, youth total (% of total labor force ages 15-24) (modeled   ILO estimate) | 1 |  
SL.UEM.TOTL.FE.ZS | Unemployment, female (% of female labor force) (modeled ILO estimate) | 1 |  
SL.UEM.TOTL.ZS | Unemployment, total (% of total labor force) (modeled ILO estimate) | 1 |  
SN.ITK.DEFC.ZS | Prevalence of undernourishment (% of population) | 1 |  
SP.POP.SCIE.RD.P6 | Researchers in R&D (per million people) | 0 |  
SP.POP.TECH.RD.P6 | Technicians in R&D (per million people) | 0 |  
SP.UWT.TFRT | Unmet need for contraception (% of married women ages 15-49) | 1 | 1
TX.MNF.TECH.ZS.UN | Medium and high-tech exports (% manufactured exports) | 1 |  
WBL | Retirement Age | 1 | 1

**Comment by tgherzog** [comment]
I've committed the changes from our 11/26 discussion to the metadata file, so I'm closing this.

**Comment by HirokoMaeda** [comment]
This is to follow up on the trivial vs non-trivial discussion for high-income countries [here](https://github.com/worldbank/ESG_gaps_research/issues/9#issuecomment-557725777). 

1. SH.MLR.INCD.P3 | Incidence of malaria (per 1,000 population at risk)
Malaria is less relevant in high income countries, since most of the them are located in malaria free climate (e.g. Europe, North America). The incidence of high income countries with malaria climate (e.g. South Korea, Saudi Arabia, and Singapore) can be considered zero in general. 

2. SL.TLF.0714.ZS | Children in employment, total (% of children ages 7-14)
Child labor is trivial. They exist in high-income countries, but the size is small (1 percent of the total number of child labors). 

3. WBL | Retirement Age | 1 | 1
There aren’t laws that set mandatory retirement age in many high-income countries such as USA. The data source will move toward a pension-based question: the statutory retirement age for a woman/man to receive a full old-age pension.

**Comment by tgherzog** [comment]
>This is to follow up on the trivial vs non-trivial discussion for high-income countries here.

Thanks, @HirokoMaeda this confirms the values already in the spreadsheet
